const defaultChecklistGroups = [
  {
    id: "sem-contato",
    title: "Sem contato com produto",
    items: [
      "Sala de preparacao do aroma",
      "Exaustor",
      "Piso fritador",
      "Coifa exaustor fritador",
      "Tanque de oleo 01",
      "Tanque de oleo 02",
      "Paineis eletricos externo",
      "Calhas eletricas",
      "Tubulacoes de agua, ar e gas",
      "Container de residuos",
      "Piso area",
      "Utensilios",
      "Paredes",
      "Selador de fardos",
      "DML",
      "Paletes limpos",
      "Escada da plataforma",
    ],
  },
  {
    id: "zona-produto",
    title: "Zona do produto",
    items: [
      "Silo vibratorio",
      "Esteira de Elevacao",
      "Fritador",
      "Tambor fritador",
      "Escorredor vibratorio",
      "Tambor de aromatizacao",
      "Esteira saida do tambor",
      "Calha de inspecao",
      "Esteira saida da calha",
      "Empacotadora 1",
      "Empacotadora 2",
      "Prato cacamba e balanca empacotadora 01",
      "Prato cacamba e balanca empacotadora 02",
      "Esteira",
    ],
  },
];

const milhoChecklistGroups = [
  {
    id: "milho-sem-contato",
    title: "Sem contato com produto",
    items: [
      "Sala de preparacao do aroma",
      "Exaustores area extrusora",
      "Escada forno",
      "Paredes area extrusora",
      "Janelas area da extrusora",
      "Paineis eletricos externos",
      "Calhas eletricas",
      "Tubulacoes de agua, ar e gas",
      "Conteiner de residuos",
      "Piso area da extrusora",
      "Utensilios",
      "Paredes",
      "Selador de fardos",
      "DML",
      "Vazamentos de agua, ar e gas",
      "Paletes limpos",
      "Equipamentos inativos",
    ],
  },
  {
    id: "milho-zona-produto",
    title: "Zona do produto",
    items: [
      "Batedor de milho",
      "Extrusora Clextral",
      "Esteira saida da Clextral",
      "Forno Clextral",
      "Tanque de aroma 01",
      "Tanque de aroma 02",
      "Batedor de preparo do aroma",
      "Esteira saida forno",
      "Tumbler de aromatizacao",
      "Calha de inspecao",
      "Esteira girafa calha/silo 01",
      "Silo pulmao 01",
      "Esteira girafa silo/empacotadora 01",
      "Esteira girafa calha/silo 02",
      "Silo pulmao 02",
      "Esteira girafa silo/empacotadora 02",
      "Prato e balanca empacotadora 01",
      "Prato e balanca empacotadora 02",
      "Prato e balanca empacotadora 03",
      "Prato e balanca empacotadora 04",
      "Prato e balanca empacotadora 05",
      "Prato e balanca empacotadora 06",
      "Prato e balanca empacotadora 07",
      "Prato e balanca empacotadora 08",
      "Empacotadora 01",
      "Empacotadora 02",
      "Empacotadora 03",
      "Empacotadora 04",
      "Empacotadora 05",
      "Empacotadora 06",
      "Empacotadora 07",
      "Empacotadora 08",
      "Forno 01",
      "Forno 02",
      "Extrusora VS",
      "Esteiras",
    ],
  },
];

const roscaChecklistGroups = [
  {
    id: "rosca-sem-contato",
    title: "Sem contato com produto",
    items: [
      "Chiller resfriamento",
      "Area de armazenamento",
      "Paredes galpao",
      "Estoque embalagens do processo",
      "Bebedouros",
      "Acrilicos corte a fio",
      "Bancada de teste saida do forno",
      "Roletes da esteira",
      "Paletes de plastico",
      "Containers de residuos",
      "Papelao / filme stretch",
      "Paredes corte a fio",
      "Estoque acucar",
      "Estoque farinha de trigo",
      "Plataforma de abastecimento de trigo",
      "Paredes automacao",
      "Piso automacao",
      "Portoes fechados",
      "Paineis eletricos",
      "Calhas eletricas",
      "Telhado automacao",
      "Piso corte a fio",
    ],
  },
  {
    id: "rosca-zona-produto",
    title: "Zona do produto",
    items: [
      "Tanque de acucar invertido",
      "Peneira e elevador acucar",
      "Abastecimento farinha",
      "Batedeira",
      "Fracionamento de insumos",
      "Carrinhos",
      "Tombador",
      "Corte a fio",
      "Esteira superior do corte a fio",
      "Esteira entrada do forno",
      "Esteira saida do forno",
      "Utensilios saida do forno",
      "Esteira resfriamento",
      "Empacotadora 01",
      "Empacotadora 02",
      "Empacotadora 03",
      "Empacotadora 04",
      "Esteiras empacotadora",
      "Escada empacotadora",
      "Prato / balancas empacotadora",
      "Seladoras",
      "Equipamentos inativos",
      "Batedeira peticitos",
      "Tombador peticitos",
      "Tubulacoes ar, agua e gas",
      "Piso batedeira",
      "Escada de acesso a batedeira",
      "Paredes batedeira",
      "Paineis eletricos",
      "Telhado batedeira",
      "Estantes e utensilios",
      "Janelas batedeira",
      "Paredes corte a fio",
      "Telhado corte a fio",
      "Mangueiras",
      "Utensilios",
      "Balanca",
      "Area de reprocesso",
      "Moedor reprocesso",
      "Portao de abastecimento piso superior",
      "Superior e laterais do forno zona 01",
      "Superior e laterais do forno zona 02",
      "Superior e laterais do forno zona 03",
      "Superior e laterais do forno zona 04",
      "Superior e laterais do forno zona 05",
      "Superior e laterais do forno zona 06",
      "Superior e laterais do forno zona 07",
    ],
  },
];

const defaultConfig = {
  checklistGroups: defaultChecklistGroups,
  produtoOptions: {
    marcas: ["Cicopal"],
    sabores: ["Original", "Bacon", "Cebola", "Churrasco"],
    gramaturas: ["35g", "45g", "90g", "140g"],
  },
  liberacaoProdutoColumns: [
    "Sabor e odor",
    "Textura",
    "Aspecto visual",
    "Peso do pacote",
    "Selagem",
    "Datador",
    "Impressao",
    "Microfuro maq. 1",
    "Temp. oleo",
    "Tempo residencia",
  ],
  avaliacaoProdutoColumns: [
    { label: "Umidade produto final", unit: "%" },
    { label: "Sal", unit: "%" },
    { label: "Temperatura de envase", unit: "deg C" },
  ],
  produtoMaquinas: Array.from({ length: 8 }, (_, index) => ({
    label: `Maquina ${String(index + 1).padStart(2, "0")}`,
    columns: ["Aspecto visual", "Sabor", "Textura", "Dimensional"],
  })),
  processoMaquinas: Array.from({ length: 8 }, (_, index) => ({
    label: `Maquina ${String(index + 1).padStart(2, "0")}`,
    columns: [
      "Datador",
      "Selagem",
      "Microfuro",
      "Caixa",
      "Etiqueta",
      "Peso",
      "Ar (mm)",
    ],
  })),
};

const milhoConfig = {
  checklistGroups: milhoChecklistGroups,
  produtoOptions: {
    marcas: ["MIC", "MIK", "ANE"],
    sabores: ["QJ", "RQ", "CB", "PZ", "PR", "CM", "GL", "CR"],
    gramaturas: ["35g", "45g", "90g", "140g"],
  },
  liberacaoProdutoColumns: [
    "Sabor e odor",
    "Textura",
    "Aspecto visual",
    "Peso do pacote",
    "Selagem",
    "Impressao",
    "Micro furo maquina 1",
    "Micro furo maquina 2",
    "Micro furo maquina 3",
    "Micro furo maquina 4",
    "Micro furo maquina 5",
    "Micro furo maquina 6",
    "Micro furo maquina 7",
    "Micro furo maquina 8",
  ],
  avaliacaoProdutoColumns: [
    { label: "Umidade produto final", unit: "%" },
    { label: "Sal", unit: "%" },
    { label: "Mescla", unit: "%" },
    { label: "Temperatura de envase", unit: "deg C" },
    { label: "Densidade", unit: "g/L" },
  ],
  produtoMaquinas: Array.from({ length: 8 }, (_, index) => ({
    label: `Maquina ${String(index + 1).padStart(2, "0")}`,
    columns: ["Aspecto visual", "Sabor", "Textura", "Dimensional"],
  })),
  processoMaquinas: Array.from({ length: 8 }, (_, index) => ({
    label: `Maquina ${String(index + 1).padStart(2, "0")}`,
    columns: [
      "Datador",
      "Selagem Microfuro",
      "Caixa Etiqueta",
      "Peso",
      "Ar (mm)",
    ],
  })),
};

const roscaConfig = {
  checklistGroups: roscaChecklistGroups,
  produtoOptions: {
    marcas: ["Cicopal", "Peticitos"],
    sabores: ["Coco", "Leite", "Chocolate", "Tradicional"],
    gramaturas: ["300g", "350g", "400g", "500g"],
  },
  liberacaoProdutoColumns: [
    "Sabor e odor",
    "Textura",
    "Aspecto visual",
    "Peso do pacote",
    "Selagem",
    "Datador",
    "Impressao",
    "Micro furo maquina 1",
    "Micro furo maquina 2",
    "Micro furo maquina 3",
    "Micro furo maquina 4",
    "Ponto de massa",
    "Peso corte a fio lado operacional",
    "Peso corte a fio lado nao operacional",
    "Peso 10 biscoitos lado operacional",
    "Peso 10 biscoitos lado nao operacional",
  ],
  avaliacaoProdutoColumns: [
    { label: "Umidade produto final", unit: "%" },
    { label: "pH biscoito", unit: "pH" },
    { label: "Temperatura de envase", unit: "deg C" },
    { label: "Brix acucar invertido", unit: "deg Bx" },
    { label: "pH acucar invertido", unit: "pH" },
  ],
  produtoMaquinas: Array.from({ length: 7 }, (_, index) => ({
    label: `Maquina ${String(index + 1).padStart(2, "0")}`,
    columns: ["Aspecto visual (cor)", "Sabor", "Textura", "Dimensional"],
  })),
  processoMaquinas: Array.from({ length: 7 }, (_, index) => ({
    label: `Maquina ${String(index + 1).padStart(2, "0")}`,
    columns: [
      "Datador",
      "Selagem Microfuro",
      "Caixa Etiqueta",
      "Peso",
      "Ar (mm)",
    ],
  })),
};

export const rgDocumentConfigs = {
  "RG.QUA.005": defaultConfig,
  "RG.QUA.004": milhoConfig,
  "RG.QUA.BA.003": roscaConfig,
};

export function getRgDocumentConfig(documentName = "") {
  const normalized = documentName.split(" - ")[0];
  return rgDocumentConfigs[normalized] ?? defaultConfig;
}
