const defaultChecklistGroups = [
  {
    id: "sem-contato",
    title: "SEM CONTATO COM O PRODUTO",
    items: [
      "Sala de preparacao do aroma",
      "Exaustor",
      "Piso fritador",
      "Coifa exaustor fritador",
      "Tanque de oleo 01",
      "Tanque de oleo 02",
      "Paineis eletricos externo",
      "Calhas eletricas",
      "Tubulacoes de agua, ar e gas",
      "Container de residuos",
      "Piso area",
      "Utensilios",
      "Paredes",
      "Selador de fardos",
      "DML",
      "Paletes limpos",
      "Escada da plataforma",
    ],
  },
  {
    id: "zona-produto",
    title: "EM CONTATO COM O PRODUTO",
    items: [
      "Silo vibratorio",
      "Esteira de Elevacao",
      "Fritador",
      "Tambor fritador",
      "Escorredor vibratorio",
      "Tambor de aromatizacao",
      "Esteira saida do tambor",
      "Calha de inspecao",
      "Esteira saida da calha",
      "Empacotadora 1",
      "Empacotadora 2",
      "Prato cacamba e balanca empacotadora 01",
      "Prato cacamba e balanca empacotadora 02",
      "Esteira",
    ],
  },
];

const milhoChecklistGroups = [
  {
    id: "milho-sem-contato",
    title: "SEM CONTATO COM O PRODUTO",
    items: [
      "Sala de preparacao do aroma",
      "Exaustores area extrusora",
      "Escada forno",
      "Paredes area extrusora",
      "Janelas area da extrusora",
      "Paineis eletricos externos",
      "Calhas eletricas",
      "Tubulacoes de agua, ar e gas",
      "Conteiner de residuos",
      "Piso area da extrusora",
      "Utensilios",
      "Paredes",
      "Selador de fardos",
      "DML",
      "Vazamentos de agua, ar e gas",
      "Paletes limpos",
      "Equipamentos inativos",
    ],
  },
  {
    id: "milho-zona-produto",
    title: "EM CONTATO COM O PRODUTO",
    items: [
      "Batedor de milho",
      "Extrusora Clextral",
      "Esteira saida da Clextral",
      "Forno Clextral",
      "Tanque de aroma 01",
      "Tanque de aroma 02",
      "Batedor de preparo do aroma",
      "Esteira saida forno",
      "Tumbler de aromatizacao",
      "Calha de inspecao",
      "Esteira girafa calha/silo 01",
      "Silo pulmao 01",
      "Esteira girafa silo/empacotadora 01",
      "Esteira girafa calha/silo 02",
      "Silo pulmao 02",
      "Esteira girafa silo/empacotadora 02",
      "Prato e balanca empacotadora 01",
      "Prato e balanca empacotadora 02",
      "Prato e balanca empacotadora 03",
      "Prato e balanca empacotadora 04",
      "Prato e balanca empacotadora 05",
      "Prato e balanca empacotadora 06",
      "Prato e balanca empacotadora 07",
      "Prato e balanca empacotadora 08",
      "Empacotadora 01",
      "Empacotadora 02",
      "Empacotadora 03",
      "Empacotadora 04",
      "Empacotadora 05",
      "Empacotadora 06",
      "Empacotadora 07",
      "Empacotadora 08",
      "Forno 01",
      "Forno 02",
      "Extrusora VS",
      "Esteiras",
    ],
  },
];

const roscaChecklistGroups = [
  {
    id: "rosca-automacao",
    title: "AUTOMAÇÃO",
    items: [
      "Chiller resfriamento",
      "Estoque açúcar",
      "Estoque farinha de trigo",
      "Plataforma de abastecimento de trigo",
      "Paredes automação",
      "Piso automação",
      "Portões (fechados)",
      "Painéis elétricos da automação",
      "Calhas elétricas",
      "Telhado automação",
      "Tanque de açúcar invertido",
      "Peneira e elevador açúcar",
      "Abastecimento farinha",
    ],
  },
  {
    id: "rosca-corte-fio",
    title: "CORTE A FIO",
    items: [
      "Piso corte a fio",
      "Paredes corte a fio",
      "Telhado corte a fio",
      "Mangueiras",
      "Painéis elétricos do corte a fio",
      "Utensílios do corte a fio",
      "Balança",
      "Área de reprocesso",
      "Moedor reprocesso",
      "Acrílicos corte a fio",
      "Esteira superior do corte a fio",
    ],
  },
  {
    id: "rosca-masseira",
    title: "MASSEIRA",
    items: [
      "Tubulações de ar, água e gás",
      "Piso batedeira",
      "Escada de acesso à batedeira",
      "Paredes batedeira",
      "Painéis elétricos da masseira",
      "Telhado batedeira",
      "Estantes e utensílios",
      "Janelas batedeira",
      "Portão de abastecimento piso superior",
      "Batedeira peticitos",
      "Tombador peticitos",
    ],
  },
  {
    id: "rosca-forno",
    title: "FORNO",
    items: [
      "Superior e laterais do forno zona 01",
      "Superior e laterais do forno zona 02",
      "Superior e laterais do forno zona 03",
      "Superior e laterais do forno zona 04",
      "Superior e laterais do forno zona 05",
      "Superior e laterais do forno zona 06",
      "Superior e laterais do forno zona 07",
      "Área de armazenamento",
      "Paredes do galpão",
      "Estoque de embalagens do processo",
    ],
  },
  {
    id: "rosca-saida-forno",
    title: "SAÍDA DO FORNO",
    items: [
      "Bancada de teste saída do forno",
      "Roletes da esteira",
      "Paletes de plástico",
      "Esteira entrada do forno",
      "Esteira saída do forno",
      "Utensílios saída do forno",
      "Esteira resfriamento",
    ],
  },
  {
    id: "rosca-empacotamento-encaixotamento",
    title: "EMPACOTAMENTO / ENCAIXOTAMENTO",
    items: [
      "Bebedouros",
      "Containers de resíduos",
      "Papelão / filme stretch",
      "Empacotadora 01",
      "Empacotadora 02",
      "Empacotadora 03",
      "Empacotadora 04",
      "Esteiras empacotadora",
      "Escada empacotadora",
      "Prato / balanças empacotadora",
      "Seladoras",
    ],
  },
];

const defaultConfig = {
  checklistGroups: defaultChecklistGroups,
  produtoOptions: {
    marcas: ["Cicopal"],
    sabores: ["Original", "Bacon", "Cebola", "Churrasco"],
    gramaturas: ["35g", "45g", "90g", "140g"],
  },
  liberacaoProdutoColumns: [
    "Sabor e odor",
    "Textura",
    "Aspecto visual",
    "Peso do pacote",
    "Selagem",
    "Datador",
    "Impressao",
    "Microfuro",
    "Temp. oleo",
    "Tempo residencia",
  ],
  avaliacaoProdutoColumns: [
    { label: "Umidade produto final", unit: "%" },
    { label: "Sal", unit: "%" },
    { label: "Temperatura de envase", unit: "deg C" },
  ],
  produtoMaquinas: Array.from({ length: 8 }, (_, index) => ({
    label: `Maquina ${String(index + 1).padStart(2, "0")}`,
    columns: ["Aspecto visual", "Sabor", "Textura", "Dimensional"],
  })),
  processoMaquinas: Array.from({ length: 8 }, (_, index) => ({
    label: `Maquina ${String(index + 1).padStart(2, "0")}`,
    columns: [
      "Datador",
      "Selagem",
      "Microfuro",
      "Caixa",
      "Etiqueta",
      "Peso",
      "Ar (mm)",
    ],
  })),
};

const milhoConfig = {
  checklistGroups: milhoChecklistGroups,
  produtoOptions: {
    marcas: ["MIC", "MIK", "ANE"],
    sabores: ["QJ", "RQ", "CB", "PZ", "PR", "CM", "GL", "CR"],
    gramaturas: ["35g", "45g", "90g", "140g"],
  },
  liberacaoProdutoColumns: [
    "Sabor e odor",
    "Textura",
    "Aspecto visual",
    "Peso do pacote",
    "Selagem",
    "Impressao",
    "Microfuro",
  ],
  avaliacaoProdutoColumns: [
    { label: "Umidade produto final", unit: "%" },
    { label: "Sal", unit: "%" },
    { label: "Mescla", unit: "%" },
    { label: "Temperatura de envase", unit: "deg C" },
    { label: "Densidade", unit: "g/L" },
  ],
  produtoMaquinas: Array.from({ length: 8 }, (_, index) => ({
    label: `Maquina ${String(index + 1).padStart(2, "0")}`,
    columns: ["Aspecto visual", "Sabor", "Textura", "Dimensional"],
  })),
  processoMaquinas: Array.from({ length: 8 }, (_, index) => ({
    label: `Maquina ${String(index + 1).padStart(2, "0")}`,
    columns: [
      "Datador",
      "Selagem Microfuro",
      "Caixa Etiqueta",
      "Peso",
      "Ar (mm)",
    ],
  })),
};

const roscaConfig = {
  checklistGroups: roscaChecklistGroups,
  produtoOptions: {
    marcas: ["Cicopal", "Peticitos"],
    sabores: ["Coco", "Leite", "Chocolate", "Tradicional"],
    gramaturas: ["300g", "350g", "400g", "500g"],
  },
  liberacaoProdutoColumns: [
    "Sabor e odor",
    "Textura",
    "Aspecto visual",
    "Peso do pacote (g)",
    "Selagem",
    "Datador",
    "Impressão",
    "Micro furo · máquina 1",
    "Micro furo · máquina 2",
    "Micro furo · máquina 3",
    "Micro furo · máquina 4",
    "Ponto de massa",
    "Peso corte a fio lado operacional",
    "Peso corte a fio lado não operacional",
    "Peso 10 biscoitos lado operacional",
    "Peso 10 biscoitos lado não operacional",
  ],
  avaliacaoProdutoColumns: [
    { label: "Umidade produto final", unit: "%" },
    { label: "pH biscoito", unit: "pH" },
    { label: "Temperatura de envase", unit: "deg C" },
    { label: "Brix acucar invertido", unit: "deg Bx" },
    { label: "pH acucar invertido", unit: "pH" },
  ],
  liberacaoMaquinas: Array.from({ length: 4 }, (_, index) => ({
    label: `Maquina ${String(index + 1).padStart(2, "0")}`,
    columns: ["Aspecto visual (cor)", "Sabor", "Textura", "Dimensional"],
  })),
  processoMaquinas: Array.from({ length: 4 }, (_, index) => ({
    label: `Maquina ${String(index + 1).padStart(2, "0")}`,
    columns: [
      "Datador",
      "Selagem Microfuro",
      "Caixa Etiqueta",
      "Peso",
      "Ar (mm)",
    ],
  })),
};

export const rgDocumentConfigs = {
  "RG.QUA.005": defaultConfig,
  "RG.QUA.004": milhoConfig,
  "RG.QUA.BA.003": roscaConfig,
};

export function getRgDocumentConfig(documentName = "") {
  const normalized = documentName.split(" - ")[0];
  return rgDocumentConfigs[normalized] ?? defaultConfig;
}
