"use client";

import { useState } from "react";
import { ArrowLeft, ArrowRight, Check, CheckCircle2, ChevronRight, Circle, ClipboardCheck, Factory, Grid2X2, Layers3, ListChecks, RotateCcw, Sparkles } from "lucide-react";

const items = ["Ausência de resíduos na masseira", "Proteções e superfícies íntegras", "Área sem contato com o produto", "Utensílios limpos e identificados", "Piso limpo e sem acúmulo"];
const models = [
  { id: "focus", label: "01 · Foco", icon: Layers3, description: "Uma decisão por tela" },
  { id: "split", label: "02 · Painel", icon: ListChecks, description: "Etapas e preenchimento lado a lado" },
  { id: "cards", label: "03 · Cartões", icon: Grid2X2, description: "Visão geral com edição rápida" },
  { id: "guided", label: "04 · Guiado", icon: Sparkles, description: "Conversa operacional assistida" }
];

export default function LaboratorioUxPage() {
  const [model, setModel] = useState("focus");
  const [index, setIndex] = useState(0);
  const [answers, setAnswers] = useState({});
  const choose = (value) => setAnswers((current) => ({ ...current, [index]: value }));
  const reset = () => { setIndex(0); setAnswers({}); };
  return <main className="min-h-screen bg-[#edf0f4] text-[#171a24]"><header className="sticky top-0 z-40 border-b border-gray-200 bg-white/90 backdrop-blur-xl"><div className="mx-auto flex max-w-[1500px] flex-wrap items-center justify-between gap-3 px-4 py-3"><div className="flex items-center gap-3"><span className="grid size-11 place-items-center rounded-2xl bg-[#202476] text-white"><Factory size={22} /></span><div><p className="text-[11px] font-black uppercase tracking-[.18em] text-[#e30613]">Cicopal · laboratório isolado</p><h1 className="text-lg font-black">Modelos para o fluxo operacional</h1></div></div><button type="button" onClick={reset} className="inline-flex min-h-11 items-center gap-2 rounded-xl border border-gray-200 bg-white px-4 font-bold"><RotateCcw size={17} />Reiniciar teste</button></div></header>
    <div className="mx-auto max-w-[1500px] p-4 lg:p-6"><section className="mb-5 rounded-3xl border border-gray-200 bg-white p-5 shadow-sm"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-xs font-black uppercase tracking-wider text-[#202476]">Escolha uma direção visual</p><h2 className="mt-1 text-2xl font-black">Quatro experiências para o mesmo checklist</h2><p className="mt-1 max-w-3xl font-semibold text-gray-500">Teste como se estivesse no tablet. As respostas são locais e não alteram o sistema nem o banco.</p></div><span className="rounded-full bg-gray-100 px-4 py-2 text-sm font-black text-gray-600">Protótipo RG003 · Higienização</span></div><div className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{models.map((item) => { const Icon = item.icon; const active = model === item.id; return <button key={item.id} type="button" onClick={() => { setModel(item.id); reset(); }} className={`flex min-h-24 items-center gap-3 rounded-2xl border-2 p-4 text-left transition ${active ? "border-[#202476] bg-[#202476] text-white shadow-lg" : "border-gray-200 bg-gray-50 hover:border-gray-400"}`}><span className={`grid size-11 place-items-center rounded-xl ${active ? "bg-white/15" : "bg-white text-[#202476]"}`}><Icon size={22} /></span><span><strong className="block">{item.label}</strong><span className={`mt-1 block text-xs font-bold ${active ? "text-white/65" : "text-gray-500"}`}>{item.description}</span></span></button>; })}</div></section>
      <div className="overflow-hidden rounded-[32px] border border-gray-200 bg-white shadow-[0_24px_70px_rgba(27,32,70,.12)]">{model === "focus" ? <FocusModel index={index} setIndex={setIndex} answers={answers} choose={choose} /> : model === "split" ? <SplitModel index={index} setIndex={setIndex} answers={answers} choose={choose} /> : model === "cards" ? <CardsModel index={index} setIndex={setIndex} answers={answers} choose={choose} /> : <GuidedModel index={index} setIndex={setIndex} answers={answers} choose={choose} />}</div>
      <footer className="mt-4 rounded-2xl border border-dashed border-gray-300 bg-white/60 p-4 text-sm font-semibold text-gray-600">Todos os modelos usam alvos de toque grandes e progresso visível, seguindo referências oficiais de acessibilidade touch e formulários em múltiplas etapas. Esta página é somente para decisão visual.</footer>
    </div></main>;
}

function StatusChoices({ value, onChange, compact = false }) { return <div className="grid grid-cols-3 gap-3">{[["C", "Conforme", "green"], ["N", "Não conforme", "red"], ["NA", "Não se aplica", "gray"]].map(([code, label, tone]) => { const active = value === code; const colors = tone === "green" ? active ? "border-green-600 bg-green-600 text-white" : "border-green-200 bg-green-50 text-green-700" : tone === "red" ? active ? "border-red-600 bg-red-600 text-white" : "border-red-200 bg-red-50 text-red-700" : active ? "border-gray-600 bg-gray-600 text-white" : "border-gray-300 bg-gray-100 text-gray-600"; return <button key={code} type="button" onClick={() => onChange(code)} className={`${compact ? "min-h-16" : "min-h-24"} rounded-2xl border-2 p-2 font-black transition active:scale-[.98] ${colors}`}><span className="block text-2xl">{code}</span><span className="text-xs">{label}</span></button>; })}</div>; }
function BottomActions({ index, setIndex, answer }) { return <footer className="grid grid-cols-2 gap-3 border-t border-gray-200 bg-white p-4"><button type="button" disabled={!index} onClick={() => setIndex((value) => Math.max(0, value - 1))} className="inline-flex min-h-16 items-center justify-center gap-2 rounded-2xl border border-gray-300 font-black disabled:opacity-30"><ArrowLeft />Voltar</button><button type="button" disabled={!answer} onClick={() => setIndex((value) => Math.min(items.length - 1, value + 1))} className="inline-flex min-h-16 items-center justify-center gap-2 rounded-2xl bg-[#202476] font-black text-white disabled:bg-gray-300">{index === items.length - 1 ? "Concluir" : "Continuar"}<ArrowRight /></button></footer>; }

function FocusModel({ index, setIndex, answers, choose }) { return <div className="grid min-h-[620px] md:grid-cols-[190px_1fr]"><aside className="flex flex-col bg-[#171b68] p-6 text-white"><p className="text-xs font-black uppercase tracking-wider text-white/55">Modelo 01</p><h3 className="mt-2 text-2xl font-black">Foco total</h3><div className="mt-10 text-center"><strong className="text-6xl">{index + 1}</strong><span className="mt-2 block font-bold text-white/50">de {items.length}</span></div><div className="mt-8 flex-1 rounded-full bg-white/10 p-1"><div className="w-full rounded-full bg-white transition-all" style={{ height: `${((index + 1) / items.length) * 100}%` }} /></div></aside><section className="flex min-w-0 flex-col"><div className="flex flex-1 flex-col justify-center p-6 md:p-12"><p className="text-xs font-black uppercase tracking-[.16em] text-[#202476]">Zona do produto · Higienização</p><h2 className="mt-4 max-w-4xl text-3xl font-black leading-tight md:text-5xl">{items[index]}</h2><p className="mb-5 mt-4 font-semibold text-gray-500">Selecione a condição observada para continuar.</p><StatusChoices value={answers[index]} onChange={choose} /></div><BottomActions index={index} setIndex={setIndex} answer={answers[index]} /></section></div>; }

function SplitModel({ index, setIndex, answers, choose }) { return <div className="grid min-h-[620px] lg:grid-cols-[390px_1fr]"><aside className="border-r border-gray-200 bg-[#f7f8fa] p-5"><p className="text-xs font-black uppercase tracking-wider text-[#202476]">Modelo 02 · painel</p><h3 className="mt-1 text-2xl font-black">Higienização</h3><p className="mt-1 text-sm font-semibold text-gray-500">Zona do produto</p><div className="mt-6 space-y-2">{items.map((item, itemIndex) => <button key={item} type="button" onClick={() => setIndex(itemIndex)} className={`flex min-h-16 w-full items-center gap-3 rounded-2xl border p-3 text-left ${index === itemIndex ? "border-[#202476] bg-white shadow-md" : "border-transparent"}`}><span className={`grid size-9 shrink-0 place-items-center rounded-full font-black ${answers[itemIndex] === "C" ? "bg-green-600 text-white" : answers[itemIndex] === "N" ? "bg-red-600 text-white" : answers[itemIndex] === "NA" ? "bg-gray-600 text-white" : "bg-gray-200 text-gray-500"}`}>{answers[itemIndex] || itemIndex + 1}</span><span className="line-clamp-2 font-bold">{item}</span></button>)}</div></aside><section className="flex flex-col"><div className="flex flex-1 flex-col justify-center p-6 lg:p-12"><span className="mb-4 w-fit rounded-full bg-blue-50 px-4 py-2 text-sm font-black text-[#202476]">Item {index + 1} de {items.length}</span><h2 className="max-w-3xl text-3xl font-black leading-tight lg:text-4xl">{items[index]}</h2><div className="mt-8"><StatusChoices value={answers[index]} onChange={choose} /></div></div><BottomActions index={index} setIndex={setIndex} answer={answers[index]} /></section></div>; }

function CardsModel({ index, setIndex, answers, choose }) { return <div className="min-h-[620px] bg-[#f4f6f8] p-5 md:p-8"><header className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-xs font-black uppercase tracking-wider text-[#202476]">Modelo 03 · visão geral</p><h3 className="mt-1 text-3xl font-black">Zona do produto</h3></div><p className="font-black text-gray-500">{Object.keys(answers).length}/{items.length} respondidos</p></header><div className="mt-6 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{items.map((item, itemIndex) => <article key={item} className={`rounded-3xl border-2 bg-white p-5 shadow-sm ${index === itemIndex ? "border-[#202476]" : "border-transparent"}`}><div className="flex items-start justify-between"><span className="grid size-10 place-items-center rounded-full bg-gray-100 font-black">{itemIndex + 1}</span>{answers[itemIndex] ? <span className={`rounded-full px-3 py-1 text-xs font-black text-white ${answers[itemIndex] === "C" ? "bg-green-600" : answers[itemIndex] === "N" ? "bg-red-600" : "bg-gray-600"}`}>{answers[itemIndex]}</span> : null}</div><h4 className="mb-5 mt-4 min-h-14 text-lg font-black leading-tight">{item}</h4><StatusChoices compact value={answers[itemIndex]} onChange={(value) => { setIndex(itemIndex); choose(value); }} /></article>)}</div><button type="button" disabled={Object.keys(answers).length < items.length} className="mt-6 min-h-16 w-full rounded-2xl bg-[#202476] text-lg font-black text-white disabled:bg-gray-300">Concluir checklist</button></div>; }

function GuidedModel({ index, setIndex, answers, choose }) { return <div className="grid min-h-[620px] bg-[#f2f4f7] lg:grid-cols-[1fr_300px]"><section className="flex flex-col p-5 md:p-8"><div className="mb-5 flex items-center gap-3"><span className="grid size-12 place-items-center rounded-2xl bg-[#202476] text-white"><ClipboardCheck /></span><div><p className="text-xs font-black uppercase text-[#202476]">Modelo 04 · guiado</p><h3 className="text-xl font-black">Assistente de inspeção</h3></div></div><div className="flex-1 space-y-4"><div className="max-w-[85%] rounded-[28px_28px_28px_8px] bg-white p-6 shadow-sm"><p className="text-sm font-bold text-gray-400">Item {index + 1} · Zona do produto</p><h2 className="mt-2 text-2xl font-black leading-tight md:text-3xl">{items[index]}</h2><p className="mt-3 font-semibold text-gray-500">Qual foi a condição encontrada?</p></div><div className="ml-auto max-w-[92%] rounded-[28px_28px_8px_28px] bg-white p-4 shadow-sm"><StatusChoices value={answers[index]} onChange={choose} /></div></div><BottomActions index={index} setIndex={setIndex} answer={answers[index]} /></section><aside className="border-l border-gray-200 bg-white p-5"><p className="text-xs font-black uppercase tracking-wider text-gray-400">Resumo ao vivo</p><div className="mt-5 space-y-3">{items.map((item, itemIndex) => <button key={item} onClick={() => setIndex(itemIndex)} className="flex w-full items-center gap-3 text-left"><span className={`grid size-8 shrink-0 place-items-center rounded-full text-xs font-black ${answers[itemIndex] ? "bg-[#202476] text-white" : "bg-gray-100 text-gray-400"}`}>{answers[itemIndex] || itemIndex + 1}</span><span className="line-clamp-2 text-sm font-bold text-gray-600">{item}</span></button>)}</div></aside></div>; }
